### ISSUE TITLE
Scraper slows to a halt

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/wikihow#63] opened 2021-09-06 04:50 UTC
https://farm.openzim.org/pipeline/d94bcb96ed84cda038293316/debug
https://farm.openzim.org/pipeline/de4bcb96ed84cda0f8293316/debug
https://farm.openzim.org/pipeline/b15bcb96ed84cda059293316/debug

One scraper halted with idle CPU, one halted at 100% CPU, another was at 100% CPU and progressing too slowly to ever complete.   All seemed to be stuck attempting to download content.

**Comment by rgaudin** [comment] 2021-09-06 06:19
Thanks; I think the throttle mechanism they warned us about is at place. @kelson42 opened a ticket on zimfarm so we enable our platform-limit feature.

**Comment by kelson42** [comment] 2021-09-06 09:00
Yes, this ticket can be considered as a duplicate of https://github.com/openzim/zimfarm/issues/641

**Comment by kevinmcmurtrie** [comment] 2021-09-11 06:12
https://farm.openzim.org/pipeline/e1ac697d20a1f4242e4c8316 locked up at 100% CPU.  I'm disabling wikihow on pixelmemory.

**Comment by kelson42** [comment] 2021-09-11 06:38
@rgaudin I hardly see how https errors returned by the wikihow backend could lead to a 100% cpu usage. To me there is a bug somewhere around this. Backend errors (or even timeouts) should reported and should lead to a stop os the scraper.

**Comment by rgaudin** [comment] 2021-09-11 15:41
> @rgaudin I hardly see how https errors returned by the wikihow backend could lead to a 100% cpu usage. To me there is a bug somewhere around this. Backend errors (or even timeouts) should reported and should lead to a stop os the scraper.

@kelson42 there is nothing about HTTPS errors in this ticket. What are you referring to?
The initial report logs clearly shows incredibly slow transfers that could be explained by the throttling mechanism on wikihow, especially given we were running multiple scrapers from the same worker.
That was closed after we implemented platform limits on zimfarm.

This new report is about a single run using all CPU. I don't know what *locked up at 100% CPU* exactly means but a worker being at 100% almost all the time is to be expected. Until videos are processed (and there are thousands per language) and uploaded to cache, those need to be converted. FFmpeg uses as much CPU as it can.

Our CPU-related config in zimfarm just sets priorities between containers but there is no overall limit as it has been designed for dedicated workers.

It's wise to disable wikihow from pixelmemory, at least until we implement the `--with[out]-videos` option; especially since videos won't make it on public ZIM files.

**Comment by kelson42** [comment] 2021-09-11 15:46
@rgaudin OK, so hypothesis is: same symptom but two different root causes. Usually the throttling of a Http server does not work on the bandwidth... but at http level. But why not, the implementation of the progression shoukd allow to see if the process is stuck or if this is just a legitimate computing running.

**Comment by rgaudin** [comment] 2021-09-11 16:21
> @rgaudin OK, so hypothesis is: same symptom but two different root causes.

No, I didn't consider the CPU thing earlier, as there was this obvious network thing they warned us about.

> Usually the throttling of a Http server does not work on the bandwidth... but at http level.

No, I've seen both. HTTP 429 is widespread nowadays because it's easier (doesn't require involving network/admin people) but reducing bandwidth is more user friendly.

I'm not saying wikiHow is doing it this way; I don't know but network transfers were crazy slow until we limited the number of parallel runs and we had zero 429. So it's possible at least.

> But why not, the implementation of the progression shoukd allow to see if the process is stuck or if this is just a legitimate computing running.

Even without actual progression, the log already shows no update for 2days at time of kill so there is definitely something to investigate.

**Comment by kevinmcmurtrie** [comment] 2021-09-11 16:22
Locked up at 100% CPU means one thread in the wikihow process is using exactly 100% of one hardware thread.  It makes no kernel calls, logs, I/O, IPC, etc.  It can go for hours before it hops to different hardware thread.

These have also locked up at 0% CPU.

Logs hint that it happens while downloading, but it's hard to trace what it's doing when there are no kernel calls.  While these scrapers _are_ running they're using 100% CPU to accomplish virtually nothing.

Whether this is a bug or some strange feature, I'm leaving it off pixelmemory.  It holds the CPU clock rate high and consumes a lot of electricity without appearing to accomplish anything.

**Comment by rgaudin** [comment] 2021-09-11 16:24
OK, thanks for the details 👍

**Comment by kelson42** [comment] 2021-09-30 12:35
@rgaudin Should we keep this ticket open? Looks like the scraper works well now that we have run one successfuly for each wikiHow!

**Closed as completed** 2021-10-01 07:51 UTC
Labels: bug, question

**Comment by kevinmcmurtrie** [comment] 2021-10-02 03:23
This is more of a general problem with the Python threading.  I've seen the ZIM scraper CPU graphs with stair steps down to 0% CPU as they lose workers.  The difference with the ZIM scrapers is that they develop a fatal memory leak once the workers are stuck/dead.  They're self-terminating but I had to kill the WikiHow scrapers manually.

The one thing that's different on my system is that scrapers will see almost no iowait time.  The Docker storage mounts use only async writes as long they stay below ~200MB/sec.  Nearly all reads come from RAM, SSD, or disk prefetch.  This could be triggering different race conditions than the other workers.
