### ISSUE TITLE
Latest wikihow tr makes only 40MB

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#127] opened 2022-05-19 14:52 UTC
https://farm.openzim.org/pipeline/680d02ebc98ea2bcf52f4826

**Comment by rgaudin** [comment] 2022-05-19 15:11
I believe this is not using the latest version:

**From this run**

```
[MainThread::2022-05-19 12:02:11,895] DEBUG:Category: COVID 19
[MainThread::2022-05-19 12:02:13,968] DEBUG:-> article: Koronavir%C3%BCs-(COVID%E2%80%9019)-Nas%C4%B1l-Tedavi-Edilir
[MainThread::2022-05-19 12:02:13,968] DEBUG:-> article: Koronavir%C3%BCs-(COVID%E2%80%9019)-Nas%C4%B1l-Anla%C5%9F%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,968] DEBUG:-> article: El-Dezenfektan-Nas%C4%B1l-Yap%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,969] DEBUG:-> article: Do%C4%9Fal-Bir-Dezenfektan-Nas%C4%B1l-Yap%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,969] DEBUG:-> article: Dezenfektan-Mendil-Nas%C4%B1l-Yap%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,969] DEBUG:-> article: T%C4%B1bbi-Maske-Nas%C4%B1l-Dikilir
[MainThread::2022-05-19 12:02:13,969] DEBUG:-> article: Koronavir%C3%BCs-COVID-19%27dan-(2020)-Nas%C4%B1l-Korunulur
[MainThread::2022-05-19 12:02:13,970] DEBUG:-> article: N95-Y%C3%BCz-Maskesi-Nas%C4%B1l-Tak%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,970] DEBUG:-> article: Koronavir%C3%BCs-(COVID-19)-A%C5%9F%C4%B1s%C4%B1na-Nas%C4%B1l-Haz%C4%B1rlan%C4%B1l%C4%B1r
[MainThread::2022-05-19 12:02:13,970] DEBUG:-> article: COVID-A%C5%9F%C4%B1s%C4%B1-Yapt%C4%B1rd%C4%B1ktan-Sonra-G%C3%BCvende-Kalma-K%C4%B1lavuzu
[MainThread::2022-05-19 12:02:18,032] DEBUG:-> article: Yeni-Koronavir%C3%BCs%27e-Kar%C5%9F%C4%B1-Nas%C4%B1l-Haz%C4%B1rl%C4%B1kl%C4%B1-Olunur
[MainThread::2022-05-19 12:02:18,033] DEBUG:-> article: T%C3%BCrkiye%27de-Yeni-Koronavir%C3%BCs-Testi-Nas%C4%B1l-Yapt%C4%B1r%C4%B1l%C4%B1r
```

**Using master code**

```
[MainThread::2022-05-19 14:59:07,200] DEBUG:Category: COVID 19
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Koronavirüs-(COVID‐19)-Nasıl-Tedavi-Edilir
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Koronavirüs-(COVID‐19)-Nasıl-Anlaşılır
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: El-Dezenfektan-Nasıl-Yapılır
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Doğal-Bir-Dezenfektan-Nasıl-Yapılır
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Dezenfektan-Mendil-Nasıl-Yapılır
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Tıbbi-Maske-Nasıl-Dikilir
[MainThread::2022-05-19 14:59:07,425] DEBUG:-> article: Koronavirüs-COVID-19'dan-(2020)-Nasıl-Korunulur
[MainThread::2022-05-19 14:59:07,426] DEBUG:-> article: N95-Yüz-Maskesi-Nasıl-Takılır
[MainThread::2022-05-19 14:59:07,426] DEBUG:-> article: Koronavirüs-(COVID-19)-Aşısına-Nasıl-Hazırlanılır
[MainThread::2022-05-19 14:59:07,426] DEBUG:-> article: COVID-Aşısı-Yaptırdıktan-Sonra-Güvende-Kalma-Kılavuzu
[MainThread::2022-05-19 14:59:07,660] DEBUG:-> article: Yeni-Koronavirüs'e-Karşı-Nasıl-Hazırlıklı-Olunur
[MainThread::2022-05-19 14:59:07,661] DEBUG:-> article: Türkiye'de-Yeni-Koronavirüs-Testi-Nasıl-Yaptırılır
```

Now I have no idea how this is possible since it pulled the image today at 11:22 and the image was updated today about an hour earlier… I've checked with online image and it's serving the new code… 

So please re-run this recipe.

**Comment by rgaudin** [comment] 2022-05-19 15:15
Marking this as duplicate of #126

**Closed as completed by rgaudin** 2022-05-19 15:15 UTC
Labels: bug, duplicate
